version: "2"
services:
  soulseek:
    build: .
    environment:
      - resize=scale
      - resolution=1280x720
    ports:
      - 6080:6080
    volumes:
      - appdata:/slsk/.SoulseekQt
      - logs:/slsk/Soulseek Chat Logs
      - downloads:/slsk/Soulseek Downloads
volumes:
  appdata:
  logs:
  downloads:
